
import { NODE_TYPES } from '../types'

// Find root node
function findRoot(nodes) {
  return nodes.find(n => n.type === NODE_TYPES.ROOT)
}

// Get all children recursively (build the document hierarchy)
function collectAllNodesByType(nodes, edges, rootId = null) {
  const result = {
    root: null,
    features: [],
    usages: [],
    commands: [],
    parameters: [],
    examples: [],
    notes: [],
    all: [...nodes]
  }
  
  nodes.forEach(node => {
    switch (node.type) {
      case NODE_TYPES.ROOT:
        result.root = node
        break
      case NODE_TYPES.FEATURE:
        result.features.push(node)
        break
      case NODE_TYPES.USAGE:
        result.usages.push(node)
        break
      case NODE_TYPES.COMMAND:
        result.commands.push(node)
        break
      case NODE_TYPES.PARAMETER:
        result.parameters.push(node)
        break
      case NODE_TYPES.EXAMPLE:
        result.examples.push(node)
        break
      case NODE_TYPES.NOTE:
        result.notes.push(node)
        break
    }
  })
  
  return result
}

// Extract skill name from root content
function extractSkillName(root) {
  const firstLine = (root.data.content || '').split('\n')[0]
  const match = firstLine.match(/^#\s*(.*)$/)
  if (match && match[1]) {
    return match[1]
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
  }
  return (root.data.title || 'openclaw-skill')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

// Extract description from root content
function extractDescription(root) {
  const content = root.data.content || ''
  const lines = content.split('\n')
  for (const line of lines) {
    if (line.trim() && !line.startsWith('#') && !line.startsWith('-')) {
      return line.trim().replace(/[#*`]/g, '')
    }
  }
  return 'OpenClaw AgentSkill'
}

// Generate SKILL.md content by aggregating all nodes' Markdown content
export function generateSkillMd(root, collected) {
  // Root content is the base (metadata)
  let content = `${root.data.content || ''}\n\n`

  // Add each section in order
  [
    { key: 'features', title: '## 功能特性' },
    { key: 'usages', title: '## 使用流程' },
    { key: 'commands', title: '## 命令说明' },
    { key: 'parameters', title: '## 参数定义' },
    { key: 'examples', title: '## 使用示例' },
    { key: 'notes', title: '## 备注说明' },
  ].forEach(({ key, title }) => {
    if (collected[key].length > 0) {
      collected[key].forEach(node => {
        // If the node content doesn't already have a heading matching the type, add it
        const hasHeading = (node.data.content || '').split('\n').some(line => 
          line.startsWith('# ') || line.startsWith('## ') || line.startsWith('### ')
        )
        if (!hasHeading) {
          content += `${title}\n\n`
        }
        content += `${node.data.content}\n\n`
      })
    }
  })

  return content.trim()
}

// Generate package.json
export function generatePackageJson(skillName, description) {
  const pkg = {
    name: skillName,
    version: '1.0.0',
    description,
    main: 'index.js',
    dependencies: {},
    keywords: ['openclaw', 'skill'],
    author: '',
    license: 'MIT'
  }

  return JSON.stringify(pkg, null, 2)
}

// Generate index.js skeleton based on commands
export function generateIndexJs(skillName, commands) {
  let code = `/**
 * ${skillName} - OpenClaw AgentSkill
 * Auto-generated by OpenClaw Skill Builder (visual mindmap)
 */

export default async function run(params, context) {
  const { message, args, toolCall } = context;
  const command = args[0] || '';

`;

  if (commands.length === 0) {
    code += `  // Add your command logic here\n`;
    code += `  return { text: "Hello from ${skillName}!" };\n`;
  } else {
    commands.forEach((cmd, index) => {
      const cmdName = (cmd.data.title || 'command')
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '');
      
      if (index === 0) {
        code += `  if (command === '${cmdName}') {\n`;
      } else {
        code += `  } else if (command === '${cmdName}') {\n`;
      }
      code += `    // ${cmd.data.title}\n`;
      code += `    // TODO: Implement this command\n`;
      code += `    return { text: "Running: ${cmd.data.title}" };\n`;
      code += `  }\n`;
    });

    const allCommands = commands.map(cmd => 
      (cmd.data.title || 'command')
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
    ).filter(Boolean);

    code += `\n  return { text: "Available commands: ${allCommands.join(', ')}" };\n`;
  }

  code += '}\n';
  return code;
}

// Main export - generate all files
export default function generateSkillFiles(nodes, edges) {
  const root = findRoot(nodes)
  if (!root) {
    throw new Error('No Root node found')
  }

  const collected = collectAllNodesByType(nodes, edges)
  const skillName = extractSkillName(root)
  const description = extractDescription(root)

  return {
    skillName,
    files: {
      'SKILL.md': generateSkillMd(root, collected),
      'package.json': generatePackageJson(skillName, description),
      'index.js': generateIndexJs(skillName, collected.commands),
      'README.md': generateReadme(skillName, description),
    }
  }
}

// Generate README.md
function generateReadme(skillName, description) {
  return `# ${skillName}

${description}

## Installation

Place this directory in your OpenClaw skills folder:

\`\`\`
cp -r ${skillName} ~/.openclaw/workspace/skills/
\`\`\`

## Usage

Use in OpenClaw with:

\`\`\`
/${skillName} [command]
\`\`\`

## Description

Auto-generated by OpenClaw Skill Builder (visual mindmap editor)
`
}

// Generate all files in structure for zip
export function all(nodes, edges) {
  return generateSkillFiles(nodes, edges)
}

// Export everything
generateSkillFiles.all = all
generateSkillFiles.generateSkillMd = generateSkillMd
generateSkillFiles.generatePackageJson = generatePackageJson
generateSkillFiles.generateIndexJs = generateIndexJs
