import { NODE_TYPES } from '../types'

function findRoot(nodes) {
  return nodes.find(n => n.type === NODE_TYPES.ROOT)
}

function collectAllNodesByType(nodes) {
  const result = {
    root: null,
    features: [],
    usages: [],
    commands: [],
    parameters: [],
    examples: [],
    notes: [],
    all: [...nodes]
  }
  
  nodes.forEach(node => {
    switch (node.type) {
      case NODE_TYPES.ROOT:
        result.root = node
        break
      case NODE_TYPES.FEATURE:
        result.features.push(node)
        break
      case NODE_TYPES.USAGE:
        result.usages.push(node)
        break
      case NODE_TYPES.COMMAND:
        result.commands.push(node)
        break
      case NODE_TYPES.PARAMETER:
        result.parameters.push(node)
        break
      case NODE_TYPES.EXAMPLE:
        result.examples.push(node)
        break
      case NODE_TYPES.NOTE:
        result.notes.push(node)
        break
    }
  })
  
  return result
}

function extractSkillName(root) {
  const firstLine = (root.data.content || '').split('\n')[0]
  const match = firstLine.match(/^#\s*(.*)$/)
  if (match && match[1]) {
    return match[1]
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
  }
  return (root.data.title || 'openclaw-skill')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

function extractDescription(root) {
  const content = root.data.content || ''
  const lines = content.split('\n')
  for (const line of lines) {
    if (line.trim() && !line.startsWith('#') && !line.startsWith('-')) {
      return line.trim().replace(/[#*`]/g, '')
    }
  }
  return 'OpenClaw AgentSkill'
}

export function generateSkillMd(root, collected) {
  let content = ''
  
  content = content + (root.data.content || '') + '\n\n'
  
  const sections = [
    { key: 'features', title: '## 功能特性' },
    { key: 'usages', title: '## 使用流程' },
    { key: 'commands', title: '## 命令说明' },
    { key: 'parameters', title: '## 参数定义' },
    { key: 'examples', title: '## 使用示例' },
    { key: 'notes', title: '## 备注说明' },
  ]
  
  sections.forEach(function(section) {
    const key = section.key
    const title = section.title
    if (collected[key] && collected[key].length > 0) {
      collected[key].forEach(function(node) {
        const hasHeading = (node.data.content || '').split('\n').some(function(line) {
          return line.startsWith('# ') || line.startsWith('## ') || line.startsWith('### ')
        })
        if (!hasHeading) {
          content = content + title + '\n\n'
        }
        content = content + node.data.content + '\n\n'
      })
    }
  })

  return content.trim()
}

export function generatePackageJson(skillName, description) {
  const pkg = {
    name: skillName,
    version: '1.0.0',
    description: description,
    main: 'index.js',
    dependencies: {},
    keywords: ['openclaw', 'skill'],
    author: '',
    license: 'MIT'
  }
  return JSON.stringify(pkg, null, 2)
}

export function generateIndexJs(skillName, commands) {
  let code = '// ' + skillName + ' - OpenClaw AgentSkill\n'
  code = code + '// Auto-generated by OpenClaw Skill Builder\n\n'
  code = code + 'export default async function run(params, context) {\n'
  code = code + "  const { message, args, toolCall } = context;\n"
  code = code + "  const command = args[0] || '';\n\n"
  
  if (commands.length === 0) {
    code = code + '  return { text: "Hello from ' + skillName + '!" };\n'
  } else {
    commands.forEach(function(cmd, index) {
      const cmdName = (cmd.data.title || 'command')
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
      
      if (index === 0) {
        code = code + "  if (command === '" + cmdName + "') {\n"
      } else {
        code = code + "  } else if (command === '" + cmdName + "') {\n"
      }
      code = code + '    // ' + cmd.data.title + '\n'
      code = code + '    return { text: "Running: ' + cmd.data.title + '" };\n'
      code = code + '  }\n'
    })

    const allCommands = commands.map(function(cmd) {
      return (cmd.data.title || 'command')
        .toLowerCase()
        .replace(/\s+/g, '-')
        .replace(/[^a-z0-9-]/g, '')
    }).filter(Boolean)

    code = code + '\n  return { text: "Available commands: ' + allCommands.join(', ') + '" };\n'
  }

  code = code + '}\n'
  return code
}

function generateReadme(skillName, description) {
  return '# ' + skillName + '\n\n' + description + '\n\n## Installation\n\nPlace this directory in your OpenClaw skills folder:\n\n```\ncp -r ' + skillName + ' ~/.openclaw/workspace/skills/\n```\n\n## Usage\n\nUse in OpenClaw with:\n\n```\n/' + skillName + ' [command]\n```\n\n## Description\n\nAuto-generated by OpenClaw Skill Builder (visual mindmap editor)\n'
}

export default function generateSkillFiles(nodes, edges) {
  const collected = collectAllNodesByType(nodes)
  const root = collected.root
  
  if (!root) {
    throw new Error('No Root node found')
  }

  const skillName = extractSkillName(root)
  const description = extractDescription(root)

  return {
    skillName: skillName,
    files: {
      'SKILL.md': generateSkillMd(root, collected),
      'package.json': generatePackageJson(skillName, description),
      'index.js': generateIndexJs(skillName, collected.commands),
      'README.md': generateReadme(skillName, description),
    }
  }
}

export function all(nodes, edges) {
  return generateSkillFiles(nodes, edges)
}
