
import { NODE_TYPES } from '../types'

// Find root node
function findRoot(nodes) {
  return nodes.find(n => n.type === NODE_TYPES.ROOT)
}

// Get all children recursively (build the document hierarchy)
function collectAllNodesByType(nodes, edges, rootId = null) {
  const result = {
    root: null,
    features: [],
    sections: [],
    markdown: [],
    all: [...nodes]
  }
  
  nodes.forEach(node => {
    switch (node.type) {
      case NODE_TYPES.ROOT:
        result.root = node
        break
      case NODE_TYPES.FEATURE:
        result.features.push(node)
        break
      case NODE_TYPES.SECTION:
        result.sections.push(node)
        break
      case NODE_TYPES.MARKDOWN:
        result.markdown.push(node)
        break
    }
  })
  
  return result
}

// Generate SKILL.md content by aggregating all nodes' Markdown content
export function generateSkillMd(root, collected) {
  const skillName = root.data.skillName || root.data.name || 'unnamed-skill'
  const rootContent = root.data.content || ''
  
  let content = `---
name: ${skillName}
description: Extract from root content
---

${rootContent}

`

  // Add sections
  if (collected.sections.length > 0) {
    collected.sections.forEach(section => {
      content += `\n${section.data.content}\n\n`
    })
  }

  // Add features
  if (collected.features.length > 0) {
    content += '\n## Features\n\n'
    collected.features.forEach(feature => {
      content += `${feature.data.content}\n\n`
    })
  }

  // Add additional markdown content
  if (collected.markdown.length > 0) {
    collected.markdown.forEach(md => {
      content += `${md.data.content}\n\n`
    })
  }

  // Add usage section if not already present
  if (!content.includes('## Usage') && !content.includes('# Usage')) {
    content += `\n## Usage\n\nUse with \`/${skillName} [command]\`\n\n`
  }

  return content.trim()
}

// Generate package.json
export function generatePackageJson(root) {
  const skillName = root.data.skillName || root.data.name || 'unnamed-skill'
  const description = root.data.content 
    ? root.data.content.split('\n')[0].replace(/^#\s*/, '').replace(/\*/g, '') 
    : 'OpenClaw AgentSkill'
  
  const pkg = {
    name: skillName,
    version: '1.0.0',
    description,
    main: 'index.js',
    dependencies: {},
    keywords: ['openclaw', 'skill'],
    author: '',
    license: 'MIT'
  }

  return JSON.stringify(pkg, null, 2)
}

// Generate index.js skeleton based on features
export function generateIndexJs(root, features) {
  const skillName = root.data.skillName || root.data.name || 'unnamed-skill'
  
  let code = `/**
 * ${skillName} - OpenClaw AgentSkill
 * Auto-generated by openclaw-skill-builder (mindmap)
 */

${features.length > 0 ? '// Import necessary tools here\n' : ''}

export default async function run(params, context) {
  const { message, args, toolCall } = context;
  \n`

  if (features.length === 0) {
    code += `  // Add your feature logic here\n`
    code += `  return { text: "Hello from ${skillName}!" };\n`
  } else {
    code += `  // Route based on command/feature\n`
    code += `  const command = args[0];\n\n`
    
    features.forEach((feature, index) => {
      // Extract feature name from title
      const featureName = (feature.data.title || `feature${index + 1}`)
        .toLowerCase()
        .replace(/\s+/g, '-')
      
      if (index === 0) {
        code += `  if (command === '${featureName}') {\n`
      } else {
        code += `  } else if (command === '${featureName}') {\n`
      }
      
      code += `    // ${feature.data.title}\n`
      code += `    // TODO: Implement ${featureName}\n`
      code += `    return { text: "Implementing: ${feature.data.title}..." };\n`
      code += `  }\n`
    })

    code += `\n  return { text: "Unknown command. Available: ${features.map(f => (f.data.title || '').toLowerCase().replace(/\s+/g, '-')).filter(Boolean).join(', ')}" };\n`
  }

  code += '}\n'
  return code
}

// Main export - generate all files
export default function generateSkillFiles(nodes, edges) {
  const root = findRoot(nodes)
  if (!root) {
    throw new Error('No root node found')
  }

  const collected = collectAllNodesByType(nodes, edges)
  const features = collected.features

  return {
    skillName: root.data.skillName || root.data.name || 'openclaw-skill',
    skillMd: generateSkillMd(root, collected),
    packageJson: generatePackageJson(root),
    indexJs: generateIndexJs(root, features),
    readme: generateReadme(root)
  }
}

// Generate README.md
function generateReadme(root) {
  const skillName = root.data.skillName || root.data.name || 'OpenClaw Skill'
  const description = root.data.content 
    ? root.data.content.split('\n')[0].replace(/^#\s*/, '').replace(/\*/g, '') 
    : 'OpenClaw AgentSkill'
  
  return `# ${skillName}

${description}

## Installation

Place this directory in your OpenClaw skills folder:

\`\`\`
cp -r ${skillName} ~/.openclaw/workspace/skills/
\`\`\`

## Usage

Use in OpenClaw with:

\`\`\`
/${skillName} [command]
\`\`\`

## Description

Auto-generated by OpenClaw Skill Builder (visual mindmap editor)
`
}

// Generate all files in structure for zip
export function all(nodes, edges) {
  const { skillName, skillMd, packageJson, indexJs, readme } = generateSkillFiles(nodes, edges)
  
  const files = {
    'SKILL.md': skillMd,
    'package.json': packageJson,
    'index.js': indexJs,
    'README.md': readme
  }

  return {
    skillName: skillName || 'openclaw-skill',
    files
  }
}

// Export everything
generateSkillFiles.all = all
generateSkillFiles.generateSkillMd = generateSkillMd
generateSkillFiles.generatePackageJson = generatePackageJson
generateSkillFiles.generateIndexJs = generateIndexJs
